# SPDX-License-Identifier: GPL-3.0
# Copyright (C) 2026 wentywenty

"""Motor error-code → human-readable name mappings."""

DM_ERROR_NAMES = {
    0x00: "DM_DOWN",
    0x01: "DM_UP",
    0x08: "OVER_VOLT",
    0x09: "UNDER_VOLT",
    0x0A: "OVER_CURRENT",
    0x0B: "MOS_OVER_TEMP",
    0x0C: "COIL_OVER_TEMP",
    0x0D: "LOST_CONN",
    0x0E: "OVER_LOAD",
}

EVO_ERROR_NAMES = {
    0x00: "NO_ERROR",
    0x01: "OVER_VOLTAGE",
    0x02: "UNDER_VOLTAGE",
    0x03: "ELECTRIC_ANGLE_ERROR",
    0x04: "DRV_ERROR",
    0x05: "BUS_OVER_CURRENT",
    0x06: "PHASE_A_OVER_CURRENT",
    0x07: "PHASE_B_OVER_CURRENT",
    0x08: "PHASE_C_OVER_CURRENT",
    0x09: "PCB_OVER_TEMP",
    0x0A: "COIL_OVER_TEMP",
    0x0B: "ENCODER_ERROR",
    0x0C: "CURRENT_SENSOR_ERROR",
    0x0D: "POSITION_OVER_LIMIT",
    0x0E: "OVER_SPEED",
    0x0F: "STALL_PROTECTION",
    0x10: "CAN_COMM_LOST",
    0x81: "ENCODER_FRAME_HEAD_CHECK_ERROR",
    0x82: "ENCODER_MULTI_TURN_ERROR",
    0x83: "ENCODER_MULTI_TURN_INTERFACE_ERROR",
    0x84: "ENCODER_EXTERNAL_INPUT_ERROR",
    0x85: "ENCODER_READ_ERROR",
    0x86: "ENCODER_ERR_OFFS",
    0x87: "ENCODER_ERR_CFG",
    0x88: "ILLEGAL_FIRMWARE",
    0x89: "GATE_DRIVER_INIT_ERROR",
    0xFF: "UNKNOWN_ERROR",
}

LRO_ERROR_NAMES = {
    0x00: "NO_ERROR",
    0x01: "MOTOR_OVERHEAT",
    0x02: "OVER_CURRENT",
    0x03: "UNDER_VOLTAGE",
    0x04: "ENCODER_ERROR",
    0x06: "BRAKE_OVERVOLT",
    0x07: "DRV_ERROR",
}

XYN_ERROR_NAMES = {
    0x00: "NO_ERROR",
    0x01: "OVER_VOLTAGE",
    0x02: "OVER_CURRENT",
    0x03: "MOTOR_OVER_TEMP",
    0x04: "BOARD_OVER_TEMP",
    0x05: "UNDER_VOLTAGE",
    0x06: "ENCODER_FAULT",
    0x07: "COMM_FAULT",
    0x08: "WARN_MOTOR_OVER_TEMP",
    0x09: "WARN_BOARD_OVER_TEMP",
}
