# SPDX-License-Identifier: GPL-3.0
# Copyright (C) 2026 wentywenty

"""Motor error-code → human-readable name mappings."""

DM_ERROR_NAMES = {
    0x00: "DM_DOWN",
    0x01: "DM_UP",
    0x08: "DM_OVER_VOLT",
    0x09: "DM_UNDER_VOLT",
    0x0A: "DM_OVER_CURRENT",
    0x0B: "DM_MOS_OVER_TEMP",
    0x0C: "DM_COIL_OVER_TEMP",
    0x0D: "DM_LOST_CONN",
    0x0E: "DM_OVER_LOAD",
}

EVO_ERROR_NAMES = {
    0x00: "EVO_NO_ERROR",
    0x01: "EVO_OVER_VOLTAGE",
    0x02: "EVO_UNDER_VOLTAGE",
    0x03: "EVO_ELECTRIC_ANGLE_ERROR",
    0x04: "EVO_DRV_ERROR",
    0x05: "EVO_BUS_OVER_CURRENT",
    0x06: "EVO_PHASE_A_OVER_CURRENT",
    0x07: "EVO_PHASE_B_OVER_CURRENT",
    0x08: "EVO_PHASE_C_OVER_CURRENT",
    0x09: "EVO_PCB_OVER_TEMP",
    0x0A: "EVO_COIL_OVER_TEMP",
    0x0B: "EVO_ENCODER_ERROR",
    0x0C: "EVO_CURRENT_SENSOR_ERROR",
    0x0D: "EVO_POSITION_OVER_LIMIT",
    0x0E: "EVO_OVER_SPEED",
    0x0F: "EVO_STALL_PROTECTION",
    0x10: "EVO_CAN_COMM_LOST",
    0x81: "EVO_ENCODER_FRAME_HEAD_CHECK_ERROR",
    0x82: "EVO_ENCODER_MULTI_TURN_ERROR",
    0x83: "EVO_ENCODER_MULTI_TURN_INTERFACE_ERROR",
    0x84: "EVO_ENCODER_EXTERNAL_INPUT_ERROR",
    0x85: "EVO_ENCODER_READ_ERROR",
    0x86: "EVO_ENCODER_ERR_OFFS",
    0x87: "EVO_ENCODER_ERR_CFG",
    0x88: "EVO_ILLEGAL_FIRMWARE",
    0x89: "EVO_GATE_DRIVER_INIT_ERROR",
    0xFF: "EVO_UNKNOWN_ERROR",
}

LRO_ERROR_NAMES = {
    0x00: "LRO_NO_ERROR",
    0x01: "LRO_MOTOR_OVERHEAT",
    0x02: "LRO_OVER_CURRENT",
    0x03: "LRO_UNDER_VOLTAGE",
    0x04: "LRO_ENCODER_ERROR",
    0x06: "LRO_BRAKE_OVERVOLT",
    0x07: "LRO_DRV_ERROR",
}

XYN_ERROR_NAMES = {
    0x00: "XYN_NO_ERROR",
    0x01: "XYN_OVER_VOLTAGE",
    0x02: "XYN_OVER_CURRENT",
    0x03: "XYN_MOTOR_OVER_TEMP",
    0x04: "XYN_BOARD_OVER_TEMP",
    0x05: "XYN_UNDER_VOLTAGE",
    0x06: "XYN_ENCODER_FAULT",
    0x07: "XYN_COMM_FAULT",
    0x08: "XYN_WARN_MOTOR_OVER_TEMP",
    0x09: "XYN_WARN_BOARD_OVER_TEMP",
}
